#!/bin/bash

sbatch --job-name=grid1_1 --array=1-25000 --partition=shared nmdm_array1.slurm /home/nfranz/NMDinStars/makeGrids/second-gridFile-0.txt 
sbatch --job-name=grid1_2 --array=1-25000 --partition=shared nmdm_array1.slurm /home/nfranz/NMDinStars/makeGrids/second-gridFile-1.txt
sbatch --job-name=grid1_3 --array=1-6250 --partition=kill-shared nmdm_array1.slurm /home/nfranz/NMDinStars/makeGrids/second-gridFile-2.txt
