#!/bin/bash
    
sbatch --job-name=sm_1 --array=1-1875 --error=error-%A.err --output=output-%A.out --partition=shared sm_array.slurm /home/nfranz/NMDinStars/makeGrids/SM-gridFile-0.txt

sbatch --job-name=sm_2 --array=1-1875 --error=error-%A.err --output=output-%A.out --partition=shared sm_array.slurm /home/nfranz/NMDinStars/makeGrids/SM-gridFile-1.txt
